name: Pull Request to Master

on: 
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
      - run: npm install -g vsce
      - run: vsce package
