name: Release

on: 
  push:
    tags:
      - 'v*'

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install VSCE
        run: npm install -g vsce
      - name: Set environment variables
        run: echo "RELEASE_TAG=$(npm run echo-version | tail -1)" >> $GITHUB_ENV
      - name: Package VSIX package
        run: vsce package
      - name: Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          files: vsc-bigquery-${{ env.RELEASE_TAG }}.vsix
          gzip: false
          body: automatic release from master
